# Generated by Django 3.1.7 on 2023-04-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230405_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
