# Generated by Django 3.1.7 on 2023-04-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230405_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_superuser',
        ),
    ]
